language: java
jdk:
- oraclejdk8
install: "./gradlew assemble"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  apt: true
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- openssl aes-256-cbc -K $encrypted_13c6474f5967_key -iv $encrypted_13c6474f5967_iv
  -in gradle.properties.enc -out gradle.properties -d
script: "./gradlew externalCiTest"
after_success:
- test $TRAVIS_BRANCH = "dev" && ./gradlew uploadArchives
group: stable
os: linux
env:
  global:
  - secure: sz9FE/tvPvDJWJSiIFo24tGkkt6+RwM62O/Zs9Nla0fPJsxpPNYnzhp243MleL5HyZDUc4zRg3BtgeeiUqC/9sqCnqt073t1ZmTBCIEsBZv4OXVhUCwCSXZsgnYqqalN+1PDSJ32EX5yByOLA/hCmXIzpis1FZ+rrOS1XeOllvR8+MRWTTspCQxnvEYLewCAv6Rv0+dkI8scK68aHtaNPyfNpIW1bIxsF3Ilo2GQaebl5t/M3XZmm3HQd92vY/bE4DIFjLk2EFHWiTTAKa6jqh8/GeZkBgKGEkBVRI0bJTIuxs2XqVBeYpgmOmlK7jbUfnGqrwvPMJ0aVhEmlM9B3gbSmNqC5SaVPTVyaFPBBuN6chAwlcasCq+EpiHo9kYjU8QBmiA5SKdVeKkiYw1e4zNjb0RjDFcFmmxC3FluqglsdF3gDD3lt+h3663XomMz1LgyXoX5hHyTARX1J1qR3kvZ4b0LWBoCczT38jk3ahznns30nsV2p5ZcNKIFme1SzHRmdUDy/FP/seBMzLGD+0gh8Zf6RnfQdxXpRiO1y6WD+6/JfcC0pP4VuR9tceeT5MEY5KZKaRoD1LCOVjM/psHQL8WiFNd3iBM+vYouMQvXCI1Asil36SyHqN60icJTg3LbNwwcSadrNhBlHg/H3Eawz/qUGlcskxD8SE6n8M4=
  - secure: a54BnOU2b9xvWfGpz90T8FY2KYANz2cbLIUd9Y57761Ec4V38ER2R4qaxAX7iHOmUiGO1BY2WmOpcrjQv2ov8S+kKDzGwRV2MceqCmDGRf2Z5SlwluKGC1qekdL4BZCCj2V2CpbIMUSuvTHRFY2hKQCce1nfz+cm3D/XwteFsh7kAWRlmG6IqxAMX6Aa0u8mpwlsTjcazbCdq9lkvYl1K3SC7G/KxRe+qaXhw46ds4ff6Je/+ObSAxRtJ4exw0ML+ldRsvZXppyo9nFgfx+PTHsmLAoNyDFlECqgzEUUu6iINB/FPa/4YjfpOI9sq2VHobeRj9rVYJSvabOwaP7xW577tz3C0PGZLbZElvIiAwlqc+bC5Kq/IHokc42M/kavGp5bqB+Sq8AQtu9KOKpR7bhNW3AM8npYGXsLyGiSkYVg2blKhFflawsFy7+qj/oOW8rEyO3vkSClO4hLuonVwdelhFgJ8UNR9TdwcR67HQTTDc59fAhNU3lK77JAQq8QvR6GYRMNGNEsapQX7WmiwirlteetFU/9ttVrhGWoQCM8C5rOUW/u30bsvxu5cXNzmyLV8ff6LiEzomKn0Sl5YdJPzZwj46vOgrCu6zwH3JmfreMWhfmiTCDORaYUMDz7CXn0s8ssk8M6r9wI6ajmlwqLZ3OiddqjcoEu2RZfAjQ=
